# ./docker-compose.yml
version: "3"

networks:
  front:

services:
  front:
    container_name: jorgemgr.com-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - "./:/app"
      - '/app/node_modules'
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    tty: true